name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 3.0.4
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_androido
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_androido:
    git:
      url: https://github.com/kilterskjalg/flutter-plugins
      path: packages/webview_flutter/webview_flutter_androido
  webview_flutter_platform_interface: ^1.9.3
  webview_flutter_wkwebview: ^2.7.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
